version: '3'
services:
   redis-server:
      image: 'redis'
   node-app:
      build: .
      ports:
         - "4000:5000"
      restart: on-failure

# Restart policies: "no", always, on-failure, unless-stopped
